#!/usr/bin/env bash
#
# setup-local-model.sh — configure the bundled Ollama service to run a large
# local model on a CPU-only host, then pull and pre-load it.
#
# What it does (all idempotent — safe to re-run):
#   1. Writes a tuning overlay (docker/ollama.tuning.yml) that keeps the model
#      resident, caps loaded models to 1, and limits parallelism — the right
#      defaults for one big model on a RAM-limited CPU box.
#   2. Ensures COMPOSE_FILE in .env enables the Ollama overlay + the tuning one.
#   3. Brings up the ollama service, pulls the model, and warms it (the slow
#      cold-load happens once here, off the request path).
#
# Usage (run from the firehouse repo root, e.g. ~/firehouse):
#   ./scripts/setup-local-model.sh
#   ./scripts/setup-local-model.sh "hf.co/owner/Some-Model-GGUF:Q4_K_M"
#
set -euo pipefail

MODEL="${1:-hf.co/mradermacher/MiroThinker-v1.5-30B-GGUF:Q5_K_M}"
ENV_FILE=".env"
BASE_OVERLAY="docker/ollama.yml"
TUNING_OVERLAY="docker/ollama.tuning.yml"

[ -f docker-compose.yml ] || { echo "ERROR: run this from the firehouse repo root (docker-compose.yml not found)."; exit 1; }
command -v docker >/dev/null || { echo "ERROR: docker is not installed/on PATH."; exit 1; }

echo "==> Model: $MODEL"

# 1) Tuning overlay (overwritten each run so it stays in sync).
cat > "$TUNING_OVERLAY" <<'YAML'
# Auto-generated by scripts/setup-local-model.sh.
# Ollama tuning for a single large model on a RAM-limited CPU host.
services:
  ollama:
    environment:
      - OLLAMA_KEEP_ALIVE=-1        # keep the model resident (no multi-minute cold reloads)
      - OLLAMA_MAX_LOADED_MODELS=1  # never hold two big models in RAM at once (OOM guard)
      - OLLAMA_NUM_PARALLEL=1       # one sequence at a time (extra slots multiply KV-cache RAM)
      - OLLAMA_LOAD_TIMEOUT=15m     # allow a big model to finish loading on CPU (default is only 5m)
YAML
echo "==> Wrote $TUNING_OVERLAY"

# 2) Ensure COMPOSE_FILE includes the base compose file + both overlays.
touch "$ENV_FILE"
if grep -q '^COMPOSE_FILE=' "$ENV_FILE"; then
  cur="$(grep '^COMPOSE_FILE=' "$ENV_FILE" | head -1 | cut -d= -f2-)"
else
  cur="docker-compose.yml"
  echo "COMPOSE_FILE=${cur}" >> "$ENV_FILE"
fi
for overlay in "$BASE_OVERLAY" "$TUNING_OVERLAY"; do
  case ":$cur:" in *":${overlay}:"*) ;; *) cur="${cur}:${overlay}" ;; esac
done
# Portable in-place edit (GNU and BSD sed).
tmp="$(mktemp)"; sed "s#^COMPOSE_FILE=.*#COMPOSE_FILE=${cur}#" "$ENV_FILE" > "$tmp" && mv "$tmp" "$ENV_FILE"
echo "==> COMPOSE_FILE=${cur}"

# 3) Bring up Ollama with the merged config.
echo "==> Starting ollama service..."
docker compose up -d ollama

echo "==> Waiting for the Ollama API..."
for _ in $(seq 1 30); do
  if docker compose exec -T ollama ollama --version >/dev/null 2>&1; then break; fi
  sleep 2
done

echo "==> Pulling model (skips layers already present)..."
docker compose exec -T ollama ollama pull "$MODEL"

echo "==> Warming the model (first cold load is slow on CPU; this does it once)..."
if ! curl -fsS -m 1200 http://localhost:11434/api/generate \
      -d "{\"model\":\"${MODEL}\",\"prompt\":\"hi\",\"stream\":false,\"keep_alive\":-1,\"options\":{\"num_predict\":1}}" \
      >/dev/null 2>&1; then
  echo "   (host curl unavailable — warming via the container instead)"
  docker compose exec -T ollama ollama run "$MODEL" "hi" >/dev/null 2>&1 || true
fi

echo "==> Resident models:"
docker compose exec -T ollama ollama ps

cat <<EOF

==> Done.
    - $MODEL is pulled and loaded, and will stay resident (OLLAMA_KEEP_ALIVE=-1).
    - Firehouse reaches it at http://ollama:11434; select it under
      Settings -> model endpoints.
    - Re-run this script any time to re-apply the config or warm the model.
EOF
